FROM debian:unstable-slim
MAINTAINER afreto kongandmarx@163.com
RUN ["apt-get","update"]
RUN ["apt-get","install","python3","-y"]
RUN ["apt","install","python3-pip","-y"]
RUN ["pip","install","pipenv"]

# docker run  -it -d -p 10119:8080 --name nodeppt -v /Users/afreto/mine/buffer:/data/ nodeppt /bin/bash
